### ISSUE TITLE
table view unhappy with updating offscreen cells

### ISSUE THREAD

**Issue by bonuelc** [MrAlek/Swift-NSFetchedResultsController-Trickery#4]
FetchControllerDelegate - didChangeObject - onUpdate calls in case .Update/.Move

"fatal error: unexpectedly found nil while unwrapping an Optional value"

Steps to reproduce:
- create enough cells to extend past the bottom of the screen
- crash on app restart (seems tableView.cellForRowAtIndexPath is returning nil)

**Comment by MrAlek** [comment]
Just fixed. Thanks for pointing the issue out!
