### ISSUE TITLE
Swift 3.0 does not compile and convert the code to 3

### ISSUE THREAD

**Issue by trevor-sonic** [MrAlek/Swift-NSFetchedResultsController-Trickery#5]
I've tried to compile but I had many compile time error

**Comment by MrAlek** [comment]
Hey Trevor, thanks for pointing it out, I'll have a look at it. Will keep you updated!

**Comment by MrAlek** [comment]
Sorry for taking so long, but now the project is updated to work with Swift 3.0. I haven't updated all the code to the new best practices since Apple changed quite a lot with iOS 10 but the basic premise of fetching meta-objects, etc still holds.
