### ISSUE TITLE
Great Resource

### ISSUE THREAD

**Issue by shaps80** [MrAlek/Swift-NSFetchedResultsController-Trickery#6]
I've been using fetched results controllers and core data for over a decade. But every time I need to remember how to do something neat like proxy sections or similar, I come back to your article (and subsequently this repo).

I don't even know how many times I've used this as a resource.

Anyway, its 2020 and we're using Swift 5+ and I still find this extremely useful as a reminder/resource when my mind goes blank.

Thank you for posting this when you did. 👍

**Comment by MrAlek** [comment]
Thank you for your kind words @shaps80! ❤️ Feels great to hear that the effort of writing the article was worth it. Good luck with your app!
